<?php

final class EntityPgFragments
{
    private const FRAGMENTS = [
        'graficas.etiquetas_total_suffix' => ') AS conteo FROM tblc_etiqueta AS e ORDER BY conteo DESC LIMIT 1 ',
        'graficas.etiquetas_list_suffix' => ') AS conteo FROM tblc_etiqueta AS e ORDER BY conteo',
        'graficas.categorias_suffix' => ') AS conteo FROM tblc_categoria AS c ORDER BY conteo DESC',
        'fragment.bitacora.121.1' => " AND MONTH(log.fecha) = '",
        'fragment.bitacora.126.2' => " AND MONTH(log.fecha) = '",
        'fragment.bitacora.132.3' => " AND YEAR(log.fecha) = '",
        'fragment.bitacora.137.4' => " AND YEAR(log.fecha) = '",
        'fragment.bitacora.141.5' => " LIMIT ",
        'fragment.bitacora_representante.35.1' => " AND fecha_acceso LIKE '%",
        'fragment.bitacora_representante.41.2' => " ORDER BY tbl_representante_movil.id_representante_movil DESC LIMIT ",
        'fragment.candidato_lista.13.1' => " and id_municipio = ",
        'fragment.candidato_lista.15.2' => " and id_estado = ",
        'fragment.candidato_lista.19.3' => " AND pe.id_estado = ",
        'fragment.candidato_lista.22.4' => " AND pe.id_municipio = ",
        'fragment.candidato_lista.25.5' => " AND c.nombre LIKE '%",
        'fragment.candidato_lista.30.6' => " AND c.id_proceso_electoral = '",
        'fragment.candidato_lista.34.7' => " ORDER BY c.ordenamiento ASC LIMIT ",
        'fragment.candidato_resultados.7.1' => " GROUP BY r.id_candidato ORDER BY suma DESC",
        'fragment.captura_masiva_registro.24.1' => " ORDER BY fecha DESC",
        'fragment.captura_masiva_registro.25.2' => " ORDER BY fecha DESC",
        'fragment.captura_masiva_registro.50.3' => " ORDER BY nombre",
        'fragment.captura_masiva_registro.61.4' => " ORDER BY nombre",
        'fragment.captura_masiva_registro.62.5' => " ORDER BY nombre",
        'fragment.captura_masiva_registro.91.6' => " and m.id_estado = ",
        'fragment.captura_masiva_registro.94.7' => " and c.id_municipio = ",
        'fragment.captura_masiva_registro.97.8' => "  ORDER BY c.id_casilla ASC",
        'fragment.casilla_electoral_listado.15.1' => " and c.id_municipio = ",
        'fragment.casilla_electoral_listado.17.2' => " and c.id_municipio = ",
        'fragment.casilla_electoral_listado.21.3' => " and m.id_estado = ",
        'fragment.casilla_electoral_listado.23.4' => " and m.id_estado = ",
        'fragment.casilla_electoral_listado.28.5' => " AND c.seccion = '",
        'fragment.casilla_electoral_listado.33.6' => " AND c.tipo = '",
        'fragment.casilla_electoral_listado.37.7' => " ORDER BY seccion ASC, tipo ASC, num_contigua ASC LIMIT ",
        'fragment.casilla_electoral_listado.39.8' => " ORDER BY c.numero ASC",
        'fragment.casilla_faltante.32.1' => " AND seccion = ",
        'fragment.casilla_resultados_lista.13.1' => " AND seccion = ",
        'fragment.casilla_resultados_lista.19.2' => " GROUP BY id_casilla LIMIT ",
        'fragment.casilla_resultados_lista.20.3' => " GROUP BY id_casilla",
        'fragment.casilla_resultados_lista.41.4' => " AND id_casilla = ",
        'fragment.casilla_resultados_lista.42.5' => " AND id_casilla = ",
        'fragment.casilla_resultados_lista.43.6' => " AND id_casilla = ",
        'fragment.casilla_resultados_lista.44.7' => " AND id_casilla = ",
        'fragment.casilla_resultados_lista.70.8' => " and id_proceso_electoral =",
        'fragment.categorias_listado.12.1' => " WHERE nombre LIKE '%",
        'fragment.categorias_listado.16.2' => " LIMIT ",
        'fragment.distrito_lista.13.1' => " and d.id_estado = ",
        'fragment.distrito_lista.16.2' => " and d.id_municipio = ",
        'fragment.distrito_lista.19.3' => " AND d.nombre LIKE '%",
        'fragment.distrito_lista.22.4' => " ORDER BY d.nombre ASC LIMIT ",
        'fragment.distrito_lista.24.5' => " ORDER BY d.nombre ASC",
        'fragment.editar_resultado.81.1' => " and id_casilla=",
        'fragment.editar_resultado.81.2' => " and idt_eleccion_c = '",
        'fragment.estados_listado.12.1' => " AND nombre LIKE '%",
        'fragment.estados_listado.16.2' => " ORDER BY nombre ASC LIMIT ",
        'fragment.estatus_casilla_lista.13.1' => " and m.id_estado = ",
        'fragment.estatus_casilla_lista.16.2' => " and c.id_municipio = ",
        'fragment.estatus_casilla_lista.19.3' => " AND ec.id_casilla = '",
        'fragment.estatus_casilla_lista.22.4' => " ORDER BY ec.fecha_hora ASC LIMIT ",
        'fragment.estatus_casilla_lista.60.5' => "  ORDER BY c.seccion ASC, c.tipo ASC, c.nombre ASC",
        'fragment.estatus_casilla_registro.24.1' => " ORDER BY fecha DESC",
        'fragment.estatus_casilla_registro.26.2' => " ORDER BY fecha DESC",
        'fragment.estatus_casilla_registro.53.3' => "  ORDER BY c.seccion ASC, c.tipo ASC, c.nombre ASC",
        'fragment.estatus_casilla_registro.55.4' => "  ORDER BY c.seccion ASC, c.tipo ASC, c.nombre ASC",
        'fragment.etiquetas_listado.13.1' => " WHERE e.etiqueta LIKE '%",
        'fragment.etiquetas_listado.17.2' => " ORDER BY e.etiqueta DESC LIMIT ",
        'fragment.grafica_eleccion.107.9' => " ORDER BY nombre",
        'fragment.grafica_eleccion.13.1' => " and id_municipio = ",
        'fragment.grafica_eleccion.14.2' => " and c.id_municipio = ",
        'fragment.grafica_eleccion.141.10' => " WHERE id_proceso_electoral = ",
        'fragment.grafica_eleccion.143.11' => " WHERE estatus = 1",
        'fragment.grafica_eleccion.147.12' => " and id_municipio = ",
        'fragment.grafica_eleccion.148.13' => " and id_municipio = ",
        'fragment.grafica_eleccion.15.3' => " and municipio_c = ",
        'fragment.grafica_eleccion.151.14' => " and id_estado = ",
        'fragment.grafica_eleccion.152.15' => " and estado_c = ",
        'fragment.grafica_eleccion.155.16' => " and id_municipio = ",
        'fragment.grafica_eleccion.156.17' => " and id_municipio = ",
        'fragment.grafica_eleccion.159.18' => " and id_estado = ",
        'fragment.grafica_eleccion.160.19' => " and estado_c = ",
        'fragment.grafica_eleccion.163.20' => " ORDER BY fecha ASC ",
        'fragment.grafica_eleccion.172.21' => " GROUP BY c.id_casilla",
        'fragment.grafica_eleccion.175.22' => " GROUP BY id_casilla",
        'fragment.grafica_eleccion.18.4' => " and id_estado = ",
        'fragment.grafica_eleccion.19.5' => " and m.id_estado = ",
        'fragment.grafica_eleccion.20.6' => " and estado_c = ",
        'fragment.grafica_eleccion.243.23' => " GROUP BY id_proceso_electoral",
        'fragment.grafica_eleccion.244.24' => " GROUP BY idcandidato_c",
        'fragment.grafica_eleccion.273.25' => " GROUP BY id_proceso_electoral",
        'fragment.grafica_eleccion.274.26' => " GROUP BY idp_politico_c",
        'fragment.grafica_eleccion.74.7' => " ORDER BY fecha DESC",
        'fragment.grafica_eleccion.96.8' => " ORDER BY nombre",
        'fragment.graficas.8.1' => " AND id_municipio = ",
        'fragment.graficas.9.2' => " AND r.id_municipio = ",
        'fragment.graficas_resultado_modal.15.1' => " and id_municipio = ",
        'fragment.graficas_resultado_modal.159.15' => " GROUP BY id_proceso_electoral",
        'fragment.graficas_resultado_modal.16.2' => " and c.id_municipio = ",
        'fragment.graficas_resultado_modal.160.16' => " GROUP BY idcandidato_c",
        'fragment.graficas_resultado_modal.17.3' => " and municipio_c = ",
        'fragment.graficas_resultado_modal.191.17' => " GROUP BY id_proceso_electoral",
        'fragment.graficas_resultado_modal.192.18' => " GROUP BY idp_politico_c",
        'fragment.graficas_resultado_modal.20.4' => " and id_estado = ",
        'fragment.graficas_resultado_modal.21.5' => " and m.id_estado = ",
        'fragment.graficas_resultado_modal.22.6' => " and estado_c = ",
        'fragment.graficas_resultado_modal.67.7' => " WHERE id_proceso_electoral = ",
        'fragment.graficas_resultado_modal.71.8' => " and id_municipio = ",
        'fragment.graficas_resultado_modal.72.9' => " and id_municipio = ",
        'fragment.graficas_resultado_modal.75.10' => " and id_estado = ",
        'fragment.graficas_resultado_modal.76.11' => " and estado_c = ",
        'fragment.graficas_resultado_modal.79.12' => " ORDER BY fecha ASC ",
        'fragment.graficas_resultado_modal.88.13' => " GROUP BY c.id_casilla",
        'fragment.graficas_resultado_modal.91.14' => " GROUP BY id_casilla",
        'fragment.importar.40.1' => " and r.id_candidato = ",
        'fragment.importar.40.2' => " and r.id_casilla = ",
        'fragment.importar.40.3' => " and r.id_representante =",
        'fragment.incidencias_registro.10.2' => " and id_municipio = ",
        'fragment.incidencias_registro.12.3' => " and m.id_estado = ",
        'fragment.incidencias_registro.13.4' => " and id_estado = ",
        'fragment.incidencias_registro.68.5' => " ORDER BY nombre",
        'fragment.incidencias_registro.85.6' => "  ORDER BY c.seccion ASC, c.tipo ASC, c.nombre ASC",
        'fragment.incidencias_registro.87.7' => "  ORDER BY c.seccion ASC, c.tipo ASC, c.nombre ASC",
        'fragment.incidencias_registro.9.1' => " and c.id_municipio = ",
        'fragment.inicio.4.1' => " AND r.id_municipio = '",
        'fragment.inicio.6.2' => " AND m.id_estado = '",
        'fragment.lista_bingo.19.1' => " AND id_casilla = ",
        'fragment.lista_candidatos.26.3' => " AND id_partido_politico = ",
        'fragment.lista_candidatos.7.1' => " AND id_casilla = ",
        'fragment.lista_candidatos.9.2' => " ORDER BY cp.ordenamiento ASC",
        'fragment.lista_candidatos2.25.1' => " AND id_casilla = ",
        'fragment.lista_candidatos2.27.2' => " ORDER BY c.ordenamiento ASC",
        'fragment.lista_candidatos2.34.3' => " AND id_candidato = ",
        'fragment.mapa_eleccion.128.10' => " ORDER BY resultado DESC LIMIT 1",
        'fragment.mapa_eleccion.17.1' => " and estado_c = ",
        'fragment.mapa_eleccion.228.11' => " ORDER BY nombre",
        'fragment.mapa_eleccion.239.12' => " ORDER BY nombre",
        'fragment.mapa_eleccion.24.2' => " and municipio_c = ",
        'fragment.mapa_eleccion.24.3' => " and estado_c = ",
        'fragment.mapa_eleccion.32.4' => " and estado_c = ",
        'fragment.mapa_eleccion.40.5' => " and municipio_c = ",
        'fragment.mapa_eleccion.51.6' => " and idt_eleccion_c = ",
        'fragment.mapa_eleccion.62.7' => " GROUP BY estado_c",
        'fragment.mapa_eleccion.81.8' => " GROUP BY municipio_c",
        'fragment.mapa_eleccion.99.9' => " GROUP BY id_casilla",
        'fragment.mapa_resultados.105.3' => " and idt_eleccion_c =",
        'fragment.mapa_resultados.105.4' => " ORDER BY resultado DESC LIMIT 1",
        'fragment.mapa_resultados.73.1' => " and idt_eleccion_c =",
        'fragment.mapa_resultados.73.2' => " GROUP BY id_casilla",
        'fragment.mapa_seccion.117.9' => " GROUP BY seccion",
        'fragment.mapa_seccion.150.10' => " GROUP BY idcandidato_c ORDER BY resultado_total DESC LIMIT 1",
        'fragment.mapa_seccion.26.1' => " and estado_c = ",
        'fragment.mapa_seccion.260.11' => " ORDER BY nombre",
        'fragment.mapa_seccion.270.12' => " ORDER BY nombre",
        'fragment.mapa_seccion.40.2' => " and municipio_c = ",
        'fragment.mapa_seccion.40.3' => " and estado_c = ",
        'fragment.mapa_seccion.50.4' => " and estado_c = ",
        'fragment.mapa_seccion.58.5' => " and municipio_c = ",
        'fragment.mapa_seccion.69.6' => " and idt_eleccion_c = ",
        'fragment.mapa_seccion.80.7' => " GROUP BY estado_c",
        'fragment.mapa_seccion.99.8' => " GROUP BY municipio_c",
        'fragment.mapa_seccion_2.115.1' => " ORDER BY nombre",
        'fragment.mapa_seccion_2.126.2' => " ORDER BY nombre",
        'fragment.municipios_listado.12.1' => " AND nombre LIKE '%",
        'fragment.municipios_listado.16.2' => " ORDER BY nombre ASC LIMIT ",
        'fragment.nominal_lista.13.1' => " AND nombre LIKE '%",
        'fragment.nominal_lista.16.2' => " ORDER BY nombre ASC LIMIT ",
        'fragment.nominal_registro.23.1' => " ORDER BY fecha DESC",
        'fragment.nominal_registro.24.2' => " ORDER BY fecha DESC",
        'fragment.nominal_registro.47.3' => " ORDER BY nombre",
        'fragment.nominal_registro.58.4' => " ORDER BY nombre",
        'fragment.nominal_registro.59.5' => " ORDER BY nombre",
        'fragment.nominal_registro.88.6' => " and m.id_estado = ",
        'fragment.nominal_registro.91.7' => " and c.id_municipio = ",
        'fragment.nominal_registro.94.8' => "  ORDER BY c.id_casilla ASC",
        'fragment.ordenar_acta_lista.9.1' => " ORDER BY cp.ordenamiento ASC",
        'fragment.partido_resultados.7.1' => " GROUP BY r.id_partido_politico ORDER BY suma DESC",
        'fragment.permisos_lista.45.1' => " AND fecha_eliminado IS NULL ORDER BY ordenamiento ASC",
        'fragment.privilegios_modulo.24.1' => ' AND fecha_eliminado IS NULL ORDER BY ordenamiento ASC',
        'fragment.proceso_electoral_lista.12.1' => " AND fecha LIKE '%",
        'fragment.proceso_electoral_lista.14.2' => " ORDER BY fecha ASC LIMIT ",
        'fragment.proceso_electoral_lista.16.3' => " ORDER BY fecha ASC ",
        'fragment.registro_bingo.10.4' => " and id_estado = ",
        'fragment.registro_bingo.42.5' => " ORDER BY fecha DESC",
        'fragment.registro_bingo.59.6' => " ORDER BY nombre",
        'fragment.registro_bingo.6.1' => " and c.id_municipio = ",
        'fragment.registro_bingo.68.7' => " ORDER BY nombre",
        'fragment.registro_bingo.69.8' => " ORDER BY nombre",
        'fragment.registro_bingo.7.2' => " and id_municipio = ",
        'fragment.registro_bingo.78.9' => "  ORDER BY c.seccion ASC, c.tipo ASC, c.nombre ASC",
        'fragment.registro_bingo.9.3' => " and m.id_estado = ",
        'fragment.registro_resultados_completo.10.4' => " and id_estado = ",
        'fragment.registro_resultados_completo.133.9' => " ORDER BY cp.ordenamiento ASC",
        'fragment.registro_resultados_completo.51.5' => " ORDER BY fecha DESC",
        'fragment.registro_resultados_completo.6.1' => " and c.id_municipio = ",
        'fragment.registro_resultados_completo.7.2' => " and id_municipio = ",
        'fragment.registro_resultados_completo.75.6' => " ORDER BY nombre",
        'fragment.registro_resultados_completo.84.7' => " ORDER BY nombre",
        'fragment.registro_resultados_completo.85.8' => " ORDER BY nombre",
        'fragment.registro_resultados_completo.9.3' => " and m.id_estado = ",
        'fragment.registro_resultados_completo_lista.21.1' => " ORDER BY cp.ordenamiento ASC",
        'fragment.reportes.148.2' => "  ORDER BY c.seccion ASC, c.tipo ASC, c.nombre ASC",
        'fragment.reportes.73.1' => " ORDER BY nombre",
        'fragment.reportes_listado.14.1' => " AND r.id_casilla = '",
        'fragment.reportes_listado.19.2' => " AND r.id_municipio = '",
        'fragment.reportes_listado.22.3' => " AND m.id_estado = '",
        'fragment.reportes_listado.26.4' => " AND r.id_municipio = '",
        'fragment.reportes_listado.31.5' => " AND m.id_estado = '",
        'fragment.reportes_listado.36.6' => " AND date_format(r.fecha_registro, '%H:%i') >= '",
        'fragment.reportes_listado.37.7' => " AND date_format(r.fecha_registro, '%H:%i') <= '",
        'fragment.reportes_listado.43.8' => " AND r.folio LIKE '%",
        'fragment.reportes_listado.48.9' => " AND r.tipo_reporte = '",
        'fragment.reportes_listado.53.10' => " AND r.tipo_registro = '",
        'fragment.reportes_listado.58.11' => " AND re.id_etiqueta = '",
        'fragment.reportes_listado.60.12' => " INNER JOIN tbl_reporte_etiqueta AS re ON r.id_reporte = re.id_reporte",
        'fragment.reportes_listado.63.13' => "
WHERE r.id_reporte != 0",
        'fragment.reportes_listado.64.14' => " ORDER BY r.fecha_registro DESC LIMIT ",
        'fragment.reportes_listado.66.15' => " WHERE r.id_reporte != 0",
        'fragment.representante_lista.13.1' => " AND m.id_estado = ",
        'fragment.representante_lista.18.2' => " AND r.id_municipio = ",
        'fragment.representante_lista.23.3' => " AND r.id_municipio = ",
        'fragment.representante_lista.27.4' => " AND r.nombre LIKE '%",
        'fragment.representante_lista.31.5' => " ORDER BY r.nombre ASC LIMIT ",
        'fragment.resultado_eleccion.46.1' => " ORDER BY fecha DESC",
        'fragment.resultado_eleccion.66.2' => " ORDER BY nombre",
        'fragment.resultado_eleccion.76.3' => " ORDER BY nombre",
        'fragment.resultado_eleccion_lista.102.14' => " GROUP BY id_casilla",
        'fragment.resultado_eleccion_lista.12.1' => " and id_municipio = ",
        'fragment.resultado_eleccion_lista.13.2' => " and c.id_municipio = ",
        'fragment.resultado_eleccion_lista.14.3' => " and municipio_c = ",
        'fragment.resultado_eleccion_lista.16.4' => " and id_estado = ",
        'fragment.resultado_eleccion_lista.17.5' => " and m.id_estado = ",
        'fragment.resultado_eleccion_lista.18.6' => " and estado_c = ",
        'fragment.resultado_eleccion_lista.25.7' => " AND c.id_proceso_electoral = '",
        'fragment.resultado_eleccion_lista.32.8' => " and pe.id_municipio = ",
        'fragment.resultado_eleccion_lista.34.9' => " and pe.id_estado = ",
        'fragment.resultado_eleccion_lista.39.10' => " and pe.id_estado = ",
        'fragment.resultado_eleccion_lista.46.11' => " and pe.id_municipio = ",
        'fragment.resultado_eleccion_lista.50.12' => " LIMIT ",
        'fragment.resultado_eleccion_lista.99.13' => " GROUP BY c.id_casilla",
        'fragment.seccion_listado.13.1' => " and m.id_estado = ",
        'fragment.seccion_listado.16.2' => " and s.id_municipio = ",
        'fragment.seccion_listado.19.3' => " AND s.nombre LIKE '%",
        'fragment.seccion_listado.21.4' => " ORDER BY s.nombre ASC LIMIT ",
        'fragment.seccion_listado.23.5' => " ORDER BY s.nombre ASC",
        'fragment.tbl_resultados.34.1' => " and idt_eleccion_c = ",
        'fragment.tbl_resultados.34.2' => " ORDER BY resultado DESC",
        'fragment.tbl_resultados_eleccion.27.1' => " and idt_eleccion_c =",
        'fragment.tbl_resultados_eleccion.38.2' => " ORDER BY idt_eleccion_c, resultado DESC",
        'fragment.tbl_resultados_eleccion_seccion.27.1' => " and idt_eleccion_c =",
        'fragment.tbl_resultados_eleccion_seccion.38.2' => " GROUP BY idcandidato_c ORDER BY idt_eleccion_c, resultado_total DESC",
        'fragment.usuarios_lista.13.1' => " AND nombre LIKE '%",
        'fragment.usuarios_lista.17.2' => " LIMIT ",
        'fragment.usuarios_registro.101.1' => " ORDER BY nombre",
    ];

    public static function has(string $key): bool
    {
        return array_key_exists($key, self::FRAGMENTS);
    }

    public static function get(string $key): string
    {
        return self::FRAGMENTS[$key];
    }
}
